### ISSUE TITLE
ttyd integration doesn't work on alpine-based kernels

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#139]
This issue is seperated from lablup/backend.ai-agent#168.    
 # Steps to reproduce
- Bind mount `terminfo` database folder to `$HOME/.terminfo`
- Start ttyd service with tmux enabled   
```sh
async def prepare_ttyd_service(service_info):
    shell = 'sh'
    if Path('/bin/bash').exists():
        shell = 'bash'
    elif Path('/bin/ash').exists():
        shell = 'ash'
    
    cmdargs = ['/opt/backend.ai/bin/ttyd',
                    f'/bin/{shell}', '-c',
                    '/opt/kernel/tmux -2 attach -t backendai || /opt/kernel/tmux -2 new -s backendai']
    return cmdargs, {}
```

# Error description
- Tmux inside ttyd doesn't start with error below
<img width="563" alt="Screen Shot 2020-02-03 at 3 01 58 PM" src="https://user-images.githubusercontent.com/2904494/73629572-f6ed3180-4696-11ea-80bd-c66d3837ed33.png">

**Comment by achimnol** [comment]
This does not work in my v19.09 development setup showing an error:
```
no current session
lost server
```

[The tmux wiki](https://github.com/tmux/tmux/wiki/FAQ#tmux-exited-with-server-exited-unexpectedly-or-lost-server-what-does-this-mean) says that this happens when the tmux server crashes.
However, there is crash dumps left (though enabled) and executing `/opt/kernel/tmux` from a shell spawned via `docker exec -i -t` works well. 🤔

**Comment by achimnol** [comment]
First, we decided to upgrade the prebuilt tmux from 2.3 to 3.0a.

**Comment by achimnol** [comment]
Closing this as stale.
