### ISSUE TITLE
Let's add GQL queries for model-serving

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#1413]
### Main idea

Related: #1278, [backend.ai-webui#1741](https://github.com/lablup/backend.ai-webui/issues/1741)

Although we already merged PR of model-serving counterpart implemented as REST API, It would be great to have GQL query for model-serving, at least for list-all services and getting service detail by its id(service-id).

In order to implement GQL queries, you may need to refer [`src/ai/backend/manager/api/service`](https://github.com/lablup/backend.ai/pull/1278/files#diff-d21fbe306a9b579a2491f344fc4de5eff8407147aac0c18568f4ca95880b27c2) module.

Here are the requests for this issue.
- [ ] Add listing query for model-service
- [ ] Add getting details of model-service by its id

**Comment by NayeonKeum** [comment]
# This issue seems duplicated

There already is an [endpoint module](https://github.com/lablup/backend.ai/blob/be16015554f7e573c8cfc0a905af82b0b31e2e0a/src/ai/backend/manager/models/endpoint.py#L201) (1:1 of service) in models which has gql queries getting from row, listing it, and etc.
Therefore I think implementing service module seems inefficient in terms of code duplcation.

## Suggestion
How about closing this issue? @lizable 

## Reference

https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/models/endpoint.py

**Comment by lizable** [comment]
@NayeonKeum It seems reasonable. But It would be nicer If you check whether the query that you pasted actually works fine or not. If does, could you close this issue and add a `duplicate` tag?

**Comment by NayeonKeum** [comment]
Works fine :) 
![스크린샷 2023-08-02 오후 1 57 22](https://github.com/lablup/backend.ai/assets/68985625/ae248754-4cd2-4d63-be5b-a0e60b896d24)
