### ISSUE TITLE
How can I use git-lfs on Backend.ai cloud?

### ISSUE THREAD

**Issue by blissray** [lablup/backend.ai#187]
**Is your feature request related to a problem? Please describe.**
I'm using git-lfs in my project. 
It doesn't seem to support to use git-lfs on cloud containers within backend.ai at this time. 
How do I install it on Backend.ai Cloud?

**Describe the solution you'd like**
Git-lfs on Backend.ai cloud

**Describe alternatives you've considered**

**Additional context**

**Comment by inureyes** [comment]
The easiest way is install git-lfs through linuxbrew. however, since it is a frequently used binary, it seems to be good to be built into the environment. I registered the issue to backend.ai-kernels repo, https://github.com/lablup/backend.ai-kernels/issues/138 so it will be prebuilt and ready to use without any installation soon.

**Comment by blissray** [comment]
Thank you for your support. Looking forward to the update

**Comment by inureyes** [comment]
@blissray git-lfs is prepared and rolling updates are in progress.
