### ISSUE TITLE
Need a exception handling on db query with wrong parameters

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai#236]
**Describe the bug**

Exception handling during db query needs to be caught.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:

* Server runs on debug mode (to find the error easily)

1. Send command via CLI with wrong parameters
2. Get the error message

**Expected behavior**

It never shows error during db query failure (event in debug mode)

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

**Client:**
 - OS: macOS 11
 - Python version: 3.9.0

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by achimnol** [comment]
Please provide one or more example commands to reproduce.

**Comment by achimnol** [comment]
This largely depends on which command you've tried, because:
 * The CLI commands consists of two categories: GraphQL-based ones and REST-based ones.
 * Our GraphQL engine has a large responsibility for picking up and translating underlying DB errors, which sometimes reduces my code-writing burden but sometimes garbles the exceptions.
 * For the REST APIs, it would be more straightforward to detect, log, and handle DB errors, but I need an example to demonstrate the error to fix it.

**Comment by achimnol** [comment]
This has no more information for more than 6 months. Closing as stale.
Please feel free to open another issue if you have concrete examples with the latest version.
