### ISSUE TITLE
Is there any tutorials?

### ISSUE THREAD

**Issue by jusonn** [lablup/backend.ai#40]
### Description
I'm looking for a hands-on tutorial but can not find it.

### Your environment

 * OS Version: 
mac os
 * Python: 
python 3.5
 * Docker: 
 * Accelerator: 
 * Backend.AI: 
   - [ ] Using cloud.backend.ai
   - [ ] Using a privately installed cluster
   - [ ] Using a demo container/VMs

**Comment by adrysn** [comment]
Sorry for the late reply. 

To run your private cluster, I think you can start from this installation documentation: http://docs.backend.ai/en/latest/install/install-from-source.html.

To use our cloud version of Backend.AI, you can visit https://cloud.backend.ai/, signup and create an access_key, secret_key pairs from the summary menu. Then, you can install `backend.ai-client-py` package like below:

```
pip install backend.ai-client~=1.4.0
```

Current Backend.AI Cloud API server is running with 1.4 version of Backend.AI and that's why you need to install client package compatible with the version. You can also refers to the documentation: https://docs.client-py.backend.ai/en/latest/index.html

We are in the process of updating our cloud API server to the latest versions, and with it, the cloud web (cloud.backend.ai) will also be transformed into much more self-contained and easy-to-use app. With that version, you don't need to create your key pairs manually, and you can launch your container sessions just by clicking. We are planning to launch the beta version of new cloud site from July, and I will comment here when the time comes.

**Comment by achimnol** [comment]
Also we have updated README for the manager and agent (if you're interested at running the server-side by yourself).
* https://github.com/lablup/backend.ai-manager/blob/master/README.md
* https://github.com/lablup/backend.ai-agent/blob/master/README.md

**Comment by achimnol** [comment]
I'm closing the issue now.
Please feel free to reopen or add comments if you have further questions.
