### ISSUE TITLE
Add support for shared memory option in creating compute session

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#52]
There is a need to set shared memory by client when creating a compute session. For docker containers, it can be set with `—shm-size=50G`.

It should be configurable by requester just like cpu and memory. It’s amount is included when determining total memory limit: total mem = mem + shred mem.

**Comment by achimnol** [comment]
We need to subtract the amount of shared memory from the memory limit of a container, since tmpfs including `/dev/shm` uses host-side kernel memory and cgroup's memory limit does not apply.

Things to do:
* [ ] manager: When checking the requested resource slot satisfies the minimum required resource slot declared by the conatiner image, use the sum of the shared memory size and the minimum required resource slot.
  - e.g., If a user launches a session with an image that requires at least 1 GiB of memory and allocates 0.5 GiB of shared memory, the user must specify at least 1.5 GiB of memory (`-r mem=1.5g`).
* [ ] agent: Subtract the amount of shared memory from the memory limit when determining the value of the memory limit for the docker container create API.

**Comment by achimnol** [comment]
LGTM! Please merge against the updated master.
