### ISSUE TITLE
'sudo' install problem

### ISSUE THREAD

**Issue by hyoseok1223** [lablup/backend.ai#542]
**Describe the bug**
`apt install sudo`
I want to install sudo, but when I use apt command, I met permission denied error

**To Reproduce**
1. `apt install sudo`
2. error occured
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

**Expected behavior**
Result of searching solution, they say `su root'. But, my root passwd isn't set. So I should use `sudo su passwd root`. but I could not use `sudo`. I'm in the loop of trouble.

**Screenshots**
![image](https://user-images.githubusercontent.com/90104418/178778866-646fcca6-6d03-41b6-91cc-d3e817c8e492.png)

**Additional context**
My college which is kmu(kookmin univ) bigdata is connected to backend.ai. Is it make some limit? Please help me

**Comment by rapsealk** [comment]
`sudo` is a predefined command; so you don't have to install it by yourself. If you want to run a command in authority of system administrator, you can just start a command with 'sudo'(e.g. `sudo apt install vim`). For the details, I recommend to refer this [wikipedia(sudo)](https://ko.wikipedia.org/wiki/Sudo). If you are familiar to unix system, you might also refer this [man7(sudo)](https://man7.org/linux/man-pages/man8/sudo.8.html).
Anyway, thank you for the first issue!

**Comment by hyoseok1223** [comment]
Thank you for your answer, but why I try to install sudo is `sudo command is not found`. ( Rethinking I want to use apt-get which require sudo root authorization ) 

But, I refer below documentation and I solved it, with `brew`. Thank you for your detail comment.
https://console.docs.backend.ai/ko/docs-essential-guide-r2/faq/faq.html


+ I have additional question, When I use fiftyone which is python base data visualization tool, it required available port number, but I don't know which port can be available for fiftyone. 
![image](https://user-images.githubusercontent.com/90104418/178884254-c3af2bbc-32f6-457f-9249-e1259b8440cc.png)

And when I use default port( It is 5151 in my environment), local host connection refused. How can i solve it? ( It's proxy or firewall probelm?) -> http://localhost:5151/
![image](https://user-images.githubusercontent.com/90104418/178885561-f3948bde-25ec-4b6b-b211-5ac2ffebd725.png)

**Comment by adrysn** [comment]
For security reasons, the environmental images do not provide `sudo` package by default. It is possible to install `sudo` package if it is needed, per-image basis. `apt` requires root privilege to update or install packages, so, it is not possible to install packages via `sudo` in your current image. As you said, linuxbrew would be an alternative package manager for non-root users.

Public mappable container port numbers are also restricted by the image label, `service-ports`. The container ports defined in the `service-ports` are only allowed to be mapped to host ports. The host ports are selected randomly, and Backend.AI automatically handles the proxy tunnel from browser to container host, so session users only need to know the container-side service port numbers to expose their service.

Currently, there seems to be no way to list the service ports inside the container. One hack to use a public port would be:
* Launch a compute session.
* Launch a app provided by the session, for example, Jupyter notebook.
* Launch a terminal app and check the container-side port number of the Jupyter server by executing `netstat` or other port monitoring tool.
* Kill the Jupyter server by `kill -9 <pid-of-jupyter>`
* Launch your application on the port number that the Jupyter server was using.
* On the browser, click Jupyter notebook icon again.
* Then, you will see your web service instead of Jupyter.

I think it is better to add an environment variable to list the service ports of a running session.

For more information on the port mapping inside a compute container, please refer to the following documentation: https://docs.backend.ai/en/latest/dev/adding-kernels.html#port-mapping-declaration

**Comment by hyoseok1223** [comment]
Thank you for your detail answer! 
It's very helpful!
