### ISSUE TITLE
Query mode execution fails for ngc-pytorch images with `query mode is disabled: failed to start jupyter kernel` error message

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#635]
**Describe the bug**
Query mode execution for the default NGC-PyTorch images fails with the container message `query mode is disabled: failed to start jupyter kernel`. The same code works with NGC-TensorFlow image, so this issue may be related to the PyTorch image.

**To Reproduce**
- Backend.AI server on x86 machine is required.
- Pull image `cr.backend.ai/lablup/testing/ngc-pytorch:22.02-py3`.
- Rescan the registry to expose the image on Backend.AI.
- Execute an inline code like the following CLI command:
  ```shell
  backend.ai run --rm -c 'print("hello")' \
    -r cpu=2 -r mem=4g -r cuda.shares=1 \
    cr.backend.ai/testing/ngc-pytorch:22.02-py3
  ```

**Expected behavior**
The output should print `hello`.

**Screenshots**
<img width="920" alt="image" src="https://user-images.githubusercontent.com/7539358/183323414-f4bff724-9276-4935-b554-70c4c4ce25fd.png">

**Comment by fregataa** [comment]
This is because jupyter-client cannot find a jupyter path.
jupyter-client resovles jupyter kernel paths in [jupyter_path()](https://github.com/jupyter/jupyter_core/blob/main/jupyter_core/paths.py#L141) method, which read environment variables.
therefore, we can resolve this problem by setting environment variable `JUPYTER_PATH` in image.

**Comment by adrysn** [comment]
Good. An example setting the variable: https://github.com/lablup/backend.ai-kernels/commit/233b01a4fbff2fffcd01aee39f4c4b7b9870f81d.
